from __future__ import annotations

from typing import Protocol


class TaskPort(Protocol):
    def create_task(self, task_text: str, dt: str | None = None) -> dict: ...

    def list_open_tasks(self, filter_date: str | None = None) -> list[dict]: ...

    def mark_task_completed(self, task_id: int) -> dict | None: ...

    def delete_task(self, task_id: int) -> bool: ...

    def delete_tasks_by_date(self, filter_date: str) -> int: ...

    def count_open_tasks(self) -> int: ...

    def delete_all_open_tasks(self) -> int: ...
